# -*- coding: utf-8 -*-
"""ml new data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZvJGW_A0dvaYZ7onYd0kuluZIqX2pOAS
"""

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

df=pd.read_csv("/content/sample_data/Hospitals1 In India (Anonymized).csv")

df.head()

df.describe()

df.tail()

df.info()

df.isnull().sum()

df.columns

numeric_df = df.select_dtypes(include=np.number)
plt.boxplot(numeric_df)
plt.show()

df.dtypes

df["State"]

df[["State"]]

df["State"].unique()

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

ohe

ohe.fit(df[["State"]])

ohe.transform(df[["State"]])

gen_ary = ohe.transform(df[["State"]])

gen_ary

ohe.categories_

df.columns

df['Rating']

df['Rating']=df['Rating'].astype("int")

df

df.drop("State",axis=1,inplace=True)

df

df.columns

df.reindex(columns=['Male','Age','EstimatedSalary','Purchased'])

df

df.columns

df['Rating'].value_counts().plot(kind="bar")

df

# The 'State' column was already dropped in a previous step.
# If you intend to drop another column, please specify it.
# Otherwise, you can remove this line as 'State' is already absent.

from sklearn.model_selection import train_test_split

X = df[['Density', 'Latitude', 'Longitude', 'Number of Reviews']]
y = df['Rating']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

X_train.shape

X_test.shape

X.shape

y_train.shape

y_train.shape

y.shape

from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier()

dt_model

dt_model.fit(X_test,y_test)

from sklearn.metrics import accuracy_score

y_pred = dt_model.predict(X_test)

accuracy_score(y_test,y_pred)*100

